language: node_js
node_js:
    - '16'

branches:
    only:
        - main

install:
    - echo "$date=$(Get-Date -format yyyyMMdd-Hmmss)"
    - echo "Start Install Dependencies"
    - npm install

before_script:
    - echo "Build Project"
    - npm run build

script:
    - echo "Package Project"

after_success:
    - echo "Build Success"

deploy:
    provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $AWS_BUCKET
    skip_cleanup: true
    upload-dir: build
    local_dir: build
    on:
        branch: main
