version: 2.1
jobs:
    build:
        working_directory: ~/project
        docker:
            -   image: circle/node:12-browsers
        steps:
            - checkout
            -   restore_cache:
                    keys:
                        - v1-dependecies-{{checksum "package-lock.json" }}
                        - v1-dependecies-
            -   run:
                    name: Install depedencies
                    command: npm install
            -   save_cache:
                    key: v1-depedencies-{{checksum "package-lock.json"}}
                    paths:
                        - node_modules
            -   run:
                    name: Build
                    command: |
                        if [ $CIRCLE_BRANCH = 'main']; then
                            npm run build
                        fi
            -   persist_to_workspace:
                    root: .
                    paths:
                        - .
    deploy:
        working_directory: ~/project
        docker:
            -   image: innovationjapan/awscli:lastest
        step:
            -   attach_workpace:
                    at: .
            -   run:
                    name: Deploy
                    command: |
                        if [$CIRCLE_BRANCH = 'main']; then
                            aws s3 sync build s3://$AWS_BUCKET --delete --exact-timestamps;
                        fi
workflows:
    build_and_deploy:
        jobs:
            -   build:
                    filters:
                        branches:
                            only:
                                - main
            -   deploy:
                    requires:
                        - build
                    filters:
                        branches:
                            only:
                                - main
